import { motion } from 'framer-motion';
import { AlertTriangle, CheckCircle2, RefreshCw, PhoneCall, Info } from 'lucide-react';

const ResultDisplay = ({ image, onReset }) => {
  // Mock data - in a real app this comes from the backend
  const results = {
    disease: "Melanocytic Nevus",
    confidence: 89.4,
    description: "A common type of skin growth that often appears as a small, dark brown spot and is caused by clusters of pigmented cells.",
    precautions: [
      "Avoid excessive sun exposure",
      "Monitor for changes in size or color",
      "Apply broad-spectrum sunscreen",
      "Consult a dermatologist if itching occurs"
    ],
    risk: "Low"
  };

  const getRiskColor = (risk) => {
    switch (risk) {
      case 'High': return 'text-red-600 bg-red-50 border-red-100';
      case 'Medium': return 'text-amber-600 bg-amber-50 border-amber-100';
      default: return 'text-accent-600 bg-accent-50 border-accent-100';
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      className="space-y-8"
    >
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-10">
        {/* Image Display */}
        <div>
          <h4 className="text-lg font-bold text-slate-900 mb-4 flex items-center space-x-2">
            <Info className="w-5 h-5 text-primary-600" />
            <span>Analyzed Image</span>
          </h4>
          <div className="rounded-[2.5rem] overflow-hidden shadow-premium h-80">
            <img src={image} alt="Analyzed" className="w-full h-full object-cover" />
          </div>
        </div>

        {/* Prediction Data */}
        <div className="flex flex-col justify-center">
          <div className="mb-6">
            <div className={`inline-flex px-4 py-1.5 rounded-full text-xs font-bold uppercase tracking-widest border mb-4 ${getRiskColor(results.risk)}`}>
              {results.risk} Risk detected
            </div>
            <h3 className="text-4xl font-extrabold text-slate-900 mb-2">{results.disease}</h3>
            <div className="flex items-center space-x-2">
              <div className="flex-1 h-3 bg-slate-100 rounded-full overflow-hidden">
                <motion.div 
                  initial={{ width: 0 }}
                  animate={{ width: `${results.confidence}%` }}
                  transition={{ duration: 1.5, ease: "easeOut" }}
                  className="h-full bg-primary-500 rounded-full"
                />
              </div>
              <span className="text-lg font-bold text-primary-600">{results.confidence}%</span>
            </div>
          </div>
          
          <p className="text-slate-600 leading-relaxed mb-6 italic">
            "{results.description}"
          </p>

          <div className="bg-slate-50 p-6 rounded-3xl border border-slate-100">
            <h5 className="font-bold text-slate-900 mb-4 flex items-center space-x-2">
              <CheckCircle2 className="w-5 h-5 text-accent-500" />
              <span>Recommended Precautions</span>
            </h5>
            <ul className="space-y-3">
              {results.precautions.map((p, i) => (
                <li key={i} className="text-sm text-slate-500 flex items-start space-x-2">
                  <span className="w-1.5 h-1.5 rounded-full bg-accent-400 mt-1.5 flex-shrink-0"></span>
                  <span>{p}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>

      {/* Advisory Note */}
      <div className="p-6 bg-primary-50 border border-primary-100 rounded-3xl flex flex-col md:flex-row items-center justify-between gap-6">
        <div className="flex items-start space-x-4">
          <div className="p-3 bg-white rounded-2xl shadow-sm">
            <AlertTriangle className="w-6 h-6 text-primary-600" />
          </div>
          <div>
            <h6 className="font-bold text-primary-900">Medical Disclaimer</h6>
            <p className="text-sm text-primary-700 leading-relaxed max-w-xl">
              This analysis is generated by AI for informational purposes only. It is NOT a professional medical diagnosis. Please consult a qualified doctor for actual medical advice.
            </p>
          </div>
        </div>
        <div className="flex space-x-3 w-full md:w-auto">
          <button 
            onClick={onReset}
            className="flex-1 md:flex-none btn bg-white text-slate-600 border border-slate-200 flex items-center justify-center space-x-2"
          >
            <RefreshCw className="w-4 h-4" />
            <span>Try Another</span>
          </button>
          <button className="flex-1 md:flex-none btn btn-primary flex items-center justify-center space-x-2">
            <PhoneCall className="w-4 h-4" />
            <span>Book Doctor</span>
          </button>
        </div>
      </div>
    </motion.div>
  );
};

export default ResultDisplay;
